services:
  - type: web
    name: par-replenishment
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
